### ISSUE TITLE
Error: Cannot find module 'antd-theme-generator'

### ISSUE THREAD

**Issue by MarkLyck** [mzohaibqc/antd-theme-webpack-plugin#79]
**Describe the bug**

When attempting to run either of the create-react-app examples I get the following error:

```
> customize-cra-sample@0.1.0 start /Users/mark/ypm/colonynetworks/antd-theme-webpack-plugin/examples/customize-cra
> react-app-rewired start

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'antd-theme-generator'
Require stack:
- /Users/mark/ypm/colonynetworks/antd-theme-webpack-plugin/index.js
- /Users/mark/ypm/colonynetworks/antd-theme-webpack-plugin/examples/customize-cra/config-overrides.js
- /Users/mark/ypm/colonynetworks/antd-theme-webpack-plugin/examples/customize-cra/node_modules/react-app-rewired/config-overrides.js
- /Users/mark/ypm/colonynetworks/antd-theme-webpack-plugin/examples/customize-cra/node_modules/react-app-rewired/scripts/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/mark/ypm/colonynetworks/antd-theme-webpack-plugin/index.js:1:27)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mark/ypm/colonynetworks/antd-theme-webpack-plugin/index.js',
    '/Users/mark/ypm/colonynetworks/antd-theme-webpack-plugin/examples/customize-cra/config-overrides.js',
    '/Users/mark/ypm/colonynetworks/antd-theme-webpack-plugin/examples/customize-cra/node_modules/react-app-rewired/config-overrides.js',
    '/Users/mark/ypm/colonynetworks/antd-theme-webpack-plugin/examples/customize-cra/node_modules/react-app-rewired/scripts/start.js'
  ]
}
```

Reproduction:
- git pull this repositoy.
- navigate to /examples/customize-cra
- run `npm i`
- run `npm start`

I tried to manually install the `antd-theme-generator` module. But that didn't fix it.

I checked node_modules and surer enough, `antd-theme-generator` is in there, and the index has an export called `getLessVars`.

I'm not sure why the config-overrides.js file is having trouble reading it.

**Comment by mzohaibqc** [comment]
@MarkLyck I've updated code as well as `cusotmize-cra` example. Have a look, hopefully you will not face this issue now.
